version: '3.6'

services:
  redis:
    image: 'redis:latest'
   # environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
    #  - ALLOW_EMPTY_PASSWORD=yes
     # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '8987:8987/tcp'
    sysctls:
      net.core.somaxconn: '65535'
    volumes:
      - ./config/redis.conf:/usr/local/redis/redis.conf:Z
    command:
      - /usr/local/redis/redis.conf

